### ISSUE TITLE
No vehicle is loaded

### ISSUE THREAD

**Issue by alexistb2904** [LambdaGaming/Automod#4]
The mod tells me that the vehicles are incompatible although I take vehicles that are supposed to be compatible

**Comment by LambdaGaming** [comment]
What vehicles are you spawning?

**Comment by alexistb2904** [comment]
I looked in the data for compatible vehicles but none worked like the bmw I8 of lw

**Comment by LambdaGaming** [comment]
Can you post the workshop links for the vehicles you're having issues with?

**Comment by alexistb2904** [comment]
https://steamcommunity.com/workshop/filedetails/?id=1400113491 The I8

**Comment by LambdaGaming** [comment]
I spawned every vehicle from that pack and they all work properly with Automod. Make sure you don't have any addons that replace the model of the I8.
